name: Dynamic README
on:
  push:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "0 * * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:
jobs:
  banner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deps
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: npm ci

      - run: node .

      - name: Add to git repo
        run: |
          git pull --rebase origin master
          git add README.md
          git config --global user.name "RevMischa Bot"
          git config --global user.email "bot@mish.dev"
          git commit -m "[Automated] README recalibrated"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://spiegelmock.com/feed/"
