name: Dynamic README
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  rewrite-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deps
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: npm ci

      - run: node .

      - name: Add to git repo
        run: |
          git add README.md
          git config --global user.name "RevMischa Bot"
          git config --global user.email "bot@mish.dev"
          git commit -m "[Automated] README recalibrated"
          git pull --rebase origin master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://spiegelmock.com/feed/"
